hit_team_names_dict = {
    'ARI': 'dbacks',
    'ATL': 'braves',
    'BAL': 'orioles',
    'BOS': 'redsox',
    'CWS': 'whitesox',
    'CHC': 'cubs',
    'CIN': 'reds',
    'CLE': 'guardians',
    'COL': 'rockies',
    'DET': 'tigers',
    'HOU': 'astros',
    'KC': 'royals',
    'LAA': 'angels',
    'LAD': 'dodgers',
    'MIA': 'marlins',
    'MIL': 'brewers',
    'MIN': 'twins',
    'NYY': 'yankees',
    'NYM': 'mets',
    'OAK': 'athletics',
    'PHI': 'phillies',
    'PIT': 'pirates',
    'SD': 'padres',
    'SF': 'giants',
    'SEA': 'mariners',
    'STL': 'cardinals',
    'TB': 'rays',
    'TEX': 'rangers',
    'TOR': 'bluejays',
    'WSH': 'nationals'
}

field_team_names_dict = {
    'dbacks': 'Arizona Diamondbacks',
    'braves': 'Atlanta Braves',
    'orioles': 'Baltimore Orioles',
    'redsox': 'Boston Red Sox',
    'whitesox': 'Chicago White Sox',
    'cubs': 'Chicago Cubs',
    'reds': 'Cincinnati Reds',
    'guardians': 'Cleveland Guardians',
    'rockies': 'Colorado Rockies',
    'tigers': 'Detroit Tigers',
    'astros': 'Houston Astros',
    'royals': 'Kansas City Royals',
    'angels': 'Los Angeles Angels',
    'dodgers': 'Los Angeles Dodgers',
    'marlins': 'Miami Marlins',
    'brewers': 'Milwaukee Brewers',
    'twins': 'Minnesota Twins',
    'yankees': 'New York Yankees',
    'mets': 'New York Mets',
    'athletics': 'Oakland Athletics',
    'phillies': 'Philadelphia Phillies',
    'pirates': 'Pittsburgh Pirates',
    'padres': 'San Diego Padres',
    'giants': 'San Francisco Giants',
    'mariners': 'Seattle Mariners',
    'cardinals': 'St. Louis Cardinals',
    'rays': 'Tampa Bay Rays',
    'rangers': 'Texas Rangers',
    'bluejays': 'Toronto Blue Jays',
    'nationals': 'Washington Nationals',
    'Arizona Diamondbacks': 'dbacks',
    'Atlanta Braves': 'braves',
    'Baltimore Orioles': 'orioles',
    'Boston Red Sox': 'redsox',
    'Chicago White Sox': 'whitesox',
    'Chicago Cubs': 'cubs',
    'Cincinnati Reds': 'reds',
    'Cleveland Guardians': 'guardians',
    'Colorado Rockies': 'rockies',
    'Detroit Tigers': 'tigers',
    'Houston Astros': 'astros',
    'Kansas City Royals': 'royals',
    'Los Angeles Angels': 'angels',
    'Los Angeles Dodgers': 'dodgers',
    'Miami Marlins': 'marlins',
    'Milwaukee Brewers': 'brewers',
    'Minnesota Twins': 'twins',
    'New York Yankees': 'yankees',
    'New York Mets': 'mets',
    'Oakland Athletics': 'athletics',
    'Philadelphia Phillies': 'phillies',
    'Pittsburgh Pirates': 'pirates',
    'San Diego Padres': 'padres',
    'San Francisco Giants': 'giants',
    'Seattle Mariners': 'mariners',
    'St Louis Cardinals': 'cardinals',
    'Tampa Bay Rays': 'rays',
    'Texas Rangers': 'rangers',
    'Toronto Blue Jays': 'bluejays',
    'Washington Nationals': 'nationals'
}